@URL = https://tareas-f45f6-default-rtdb.firebaseio.com/
###GET
GET {{URL}}/tareas.json

###POST
POST {{URL}}/tareas.json
Content-Type: application/json

{
    "titulo": "Tarea",
    "progreso": "En Progreso",
    "dificultad": "Dificil",
    "descripcion": "Mi descripcion"
}

###DELETE
DELETE {{URL}}/tareas/-MlROXUFQTjGrbVII8nJ.json

###GET 1 TAREA
PUT {{URL}}/tareas/-MlfOkL7qctnd-W4D3zI.json
Content-Type: application/json

{
  "descripcion": "MODIFICADO",
  "dificultad": "Dificil",
  "progreso": "Sin empezar",
  "titulo": "Tarea 1"
}